using System.ComponentModel;

namespace DiGi.BDOT10k.Enums
{
    public enum OT_FunSzczegolowaBudynku
    {
        [Description("apteka")] apteka,
        [Description("archiwum")] archiwum,
        [Description("areszt śledczy")] areszt_sledczy,
        [Description("bacówka")] bacowka,
        [Description("bank")] bank,
        [Description("basen kąpielowy")] basen_kapielowy,
        [Description("biblioteka")] biblioteka,
        [Description("budynek gospodarczy")] budynek_gospodarczy,
        [Description("budynek jednorodzinny")] budynek_jednorodzinny,
        [Description("budynek kontroli ruchu kolejowego")] budynek_kontroli_ruchu_kolejowego,
        [Description("budynek kontroli ruchu powietrznego")] budynek_kontroli_ruchu_powietrznego,
        [Description("budynek ogrodu zoologicznego lub botanicznego")] budynek_ogrodu_zoologicznego_lub_botanicznego,
        [Description("budynek produkcyjny zwierząt hodowlanych")] budynek_produkcyjny_zwierzat_hodowlanych,
        [Description("budynek spedycji")] budynek_spedycji,
        [Description("budynek wielorodzinny")] budynek_wielorodzinny,
        [Description("budynki cmentarne")] budynki_cmentarne,
        [Description("centrum handlowe")] centrum_handlowe,
        [Description("centrum informacyjne")] centrum_informacyjne,
        [Description("centrum konferencyjne")] centrum_konferencyjne,
        [Description("centrum telekomunikacyjne")] centrum_telekomunikacyjne,
        [Description("cerkiew")] cerkiew,
        [Description("chłodnia")] chlodnia,
        [Description("dom dla bezdomnych")] dom_dla_bezdomnych,
        [Description("dom dziecka")] dom_dziecka,
        [Description("dom kultury")] dom_kultury,
        [Description("dom letniskowy")] dom_letniskowy,
        [Description("dom opieki społecznej")] dom_opieki_spolecznej,
        [Description("dom parafialny")] dom_parafialny,
        [Description("dom pogrzebowy")] dom_pogrzebowy,
        [Description("dom rekolekcyjny")] dom_rekolekcyjny,
        [Description("dom studencki")] dom_studencki,
        [Description("dom towarowy lub handlowy")] dom_towarowy_lub_handlowy,
        [Description("dom weselny")] dom_weselny,
        [Description("dom wypoczynkowy")] dom_wypoczynkowy,
        [Description("dom zakonny")] dom_zakonny,
        [Description("domek kempingowy")] domek_kempingowy,
        [Description("dworzec autobusowy")] dworzec_autobusowy,
        [Description("dworzec kolejowy")] dworzec_kolejowy,
        [Description("dworzec lotniczy")] dworzec_lotniczy,
        [Description("dzwonnica")] dzwonnica,
        [Description("elektrociepłownia")] elektrocieplownia,
        [Description("elektrownia")] elektrownia,
        [Description("elewator")] elewator,
        [Description("filharmonia")] filharmonia,
        [Description("galeria sztuki")] galeria_sztuki,
        [Description("garaż")] garaz,
        [Description("hala sportowa")] hala_sportowa,
        [Description("hala targowa")] hala_targowa,
        [Description("hala widowiskowa")] hala_widowiskowa,
        [Description("hala wystawowa")] hala_wystawowa,
        [Description("halowy tor gokartowy")] halowy_tor_gokartowy,
        [Description("hangar")] hangar,
        [Description("hipermarket lub supermarket")] hipermarket_lub_supermarket,
        [Description("hospicjum")] hospicjum,
        [Description("hotel")] hotel,
        [Description("hotel robotniczy")] hotel_robotniczy,
        [Description("inna placówka edukacyjna")] inna_placowka_edukacyjna,
        [Description("inny budynek kultu religijnego")] inny_budynek_kultu_religijnego,
        [Description("inny urząd administracji publicznej")] inny_urzad_administracji_publicznej,
        [Description("internat lub bursa szkolna")] internat_lub_bursa_szkolna,
        [Description("izba wytrzeźwień")] izba_wytrzezwien,
        [Description("jednostka ratownictwa medycznego")] jednostka_ratownictwa_medycznego,
        [Description("kapitanat lub bosmanat portu")] kapitanat_lub_bosmanat_portu,
        [Description("kaplica")] kaplica,
        [Description("kasyno")] kasyno,
        [Description("kino")] kino,
        [Description("klasztor")] klasztor,
        [Description("klinika weterynaryjna")] klinika_weterynaryjna,
        [Description("klub sportowy")] klub_sportowy,
        [Description("klub, dyskoteka")] klub_dyskoteka,
        [Description("korty tenisowe")] korty_tenisowe,
        [Description("koszary")] koszary,
        [Description("kościół")] kosciol,
        [Description("kotłownia")] kotlownia,
        [Description("krematorium")] krematorium,
        [Description("kręgielnia")] kregielnia,
        [Description("kuria metropolitalna")] kuria_metropolitalna,
        [Description("latarnia morska")] latarnia_morska,
        [Description("leśniczówka")] lesniczowka,
        [Description("lokomotywownia lub wagonownia")] lokomotywownia_lub_wagonownia,
        [Description("magazyn")] magazyn,
        [Description("meczet")] meczet,
        [Description("ministerstwo")] ministerstwo,
        [Description("młyn")] mlyn,
        [Description("motel")] motel,
        [Description("muzeum")] muzeum,
        [Description("myjnia samochodowa")] myjnia_samochodowa,
        [Description("obserwatorium lub planetarium")] obserwatorium_lub_planetarium,
        [Description("opera")] opera,
        [Description("ośrodek pomocy społecznej")] osrodek_pomocy_spolecznej,
        [Description("ośrodek szkoleniowo-wypoczynkowy")] osrodek_szkoleniowo_wypoczynkowy,
        [Description("parking wielopoziomowy")] parking_wielopoziomowy,
        [Description("obiekt handlowo-usługowy")] obiekt_handlowo_uslugowy,
        [Description("pawilon ogrodowy lub oranżeria")] pawilon_ogrodowy_lub_oranzeria,
        [Description("pensjonat")] pensjonat,
        [Description("placówka badawcza")] placowka_badawcza,
        [Description("placówka dyplomatyczna lub konsularna")] placowka_dyplomatyczna_lub_konsularna,
        [Description("placówka ochrony zdrowia")] placowka_ochrony_zdrowia,
        [Description("placówka operatora pocztowego")] placowka_operatora_pocztowego,
        [Description("placówka opiekuńczo-wychowawcza")] placowka_opiekunczo_wychowawcza,
        [Description("policja")] policja,
        [Description("produkcyjny")] produkcyjny,
        [Description("prokuratura")] prokuratura,
        [Description("przedszkole")] przedszkole,
        [Description("przejście graniczne")] przejscie_graniczne,
        [Description("rafineria")] rafineria,
        [Description("restauracja")] restauracja,
        [Description("rezydencja ambasadora")] rezydencja_ambasadora,
        [Description("rezydencja biskupia")] rezydencja_biskupia,
        [Description("rezydencja prezydencka")] rezydencja_prezydencka,
        [Description("sala gimnastyczna")] sala_gimnastyczna,
        [Description("sanatorium")] sanatorium,
        [Description("sąd")] sad,
        [Description("schronisko dla nieletnich")] schronisko_dla_nieletnich,
        [Description("schronisko dla zwierząt")] schronisko_dla_zwierzat,
        [Description("schronisko turystyczne")] schronisko_turystyczne,
        [Description("siedziba firmy lub firm")] siedziba_firmy_lub_firm,
        [Description("silos")] silos,
        [Description("spalarnia śmieci")] spalarnia_smieci,
        [Description("stacja gazowa")] stacja_gazowa,
        [Description("stacja hydrologiczna")] stacja_hydrologiczna,
        [Description("stacja kolejki górskiej lub wyciągu krzesełkowego")] stacja_kolejki_gorskiej_lub_wyciagu_krzeselkowego,
        [Description("stacja krwiodawstwa")] stacja_krwiodawstwa,
        [Description("stacja meteorologiczna")] stacja_meteorologiczna,
        [Description("stacja nadawcza radia i telewizji")] stacja_nadawcza_radia_i_telewizji,
        [Description("stacja nautyczna")] stacja_nautyczna,
        [Description("stacja obsługi pojazdów")] stacja_obslugi_pojazdow,
        [Description("stacja paliw")] stacja_paliw,
        [Description("stacja pomp")] stacja_pomp,
        [Description("stacja sanitarno-epidemiologiczna")] stacja_sanitarno_epidemiologiczna,
        [Description("stacja transformatorowa")] stacja_transformatorowa,
        [Description("stajnia")] stajnia,
        [Description("starostwo powiatowe")] starostwo_powiatowe,
        [Description("straż graniczna")] straz_graniczna,
        [Description("straż pożarna")] straz_pozarna,
        [Description("strzelnica")] strzelnica,
        [Description("synagoga")] synagoga,
        [Description("szklarnia lub cieplarnia")] szklarnia_lub_cieplarnia,
        [Description("szkoła podstawowa")] szkola_podstawowa,
        [Description("szkoła ponadpodstawowa")] szkola_ponadpodstawowa,
        [Description("szkoła wyższa")] szkoła_wyzsza,
        [Description("szpital")] szpital,
        [Description("sztuczne lodowisko")] sztuczne_lodowisko,
        [Description("teatr")] teatr,
        [Description("terminal portowy")] terminal_portowy,
        [Description("toaleta publiczna")] toaleta_publiczna,
        [Description("ujeżdżalnia")] ujezdzalnia,
        [Description("urząd celny")] urzad_celny,
        [Description("urząd gminy")] urzad_gminy,
        [Description("urząd marszałkowski")] urzad_marszalkowski,
        [Description("urząd miasta")] urzad_miasta,
        [Description("urząd miasta i gminy")] urzad_miasta_i_gminy,
        [Description("urząd wojewódzki")] urzad_wojewodzki,
        [Description("warsztat remontowo-naprawczy")] warsztat_remontowo_naprawczy,
        [Description("wiatrak")] wiatrak,
        [Description("zabudowania koszarowe")] zabudowania_koszarowe,
        [Description("zabytek niepełniący żadnej funkcji użytkowej")] zabytek_niepelniacy_zadnej_funkcji_uzytkowej,
        [Description("zajazd")] zajazd,
        [Description("zajezdnia autobusowa")] zajezdnia_autobusowa,
        [Description("zajezdnia tramwajowa")] zajezdnia_tramwajowa,
        [Description("zajezdnia trolejbusowa")] zajezdnia_trolejbusowa,
        [Description("zakład karny")] zaklad_karny,
        [Description("zakład karny lub poprawczy")] zaklad_karny_lub_poprawczy,
        [Description("zakład poprawczy")] zaklad_poprawczy,
        [Description("zbiornik na ciecz")] zbiornik_na_ciecz,
        [Description("zbiornik na gaz")] zbiornik_na_gaz,
        [Description("żłobek")] zlobek,
    }
}
